### ISSUE TITLE
New bios is available. Please check it

### ISSUE THREAD

**Issue by Masaya-kun** [dclive/B660M-HDV-i5-1200F-Hackintosh#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dclive** [comment]
Will do, thanks!  More news soon.

**Comment by dclive** [comment]
Works great.  Results updated.  I do suggest jumping to the latest BIOS (presently 12.01), even if the speeds in my one test were 1% or 2% slower.
